In [19]:
import os
import zipfile
import pandas as pd
from langdetect import detect_langs, LangDetectException

In [35]:
comments_zip = "../data/raw/comments.zip"
entries_zip = "../data/raw/entries1.zip"
likes_zip = "../data/raw/likes.zip"

comments_dir = "../data/raw/comments_extracted"
entries_dir = "../data/raw/entries1_extracted"
likes_dir = "../data/raw/likes_extracted"

os.makedirs(comments_dir, exist_ok=True)
os.makedirs(entries_dir, exist_ok=True)
os.makedirs(likes_dir, exist_ok=True)

In [36]:
with zipfile.ZipFile(comments_zip, "r") as z:
    z.extractall(comments_dir)

with zipfile.ZipFile(entries_zip, "r") as z:
    z.extractall(entries_dir)

with zipfile.ZipFile(likes_zip, "r") as z:
    z.extractall(likes_dir)

print("Extraction complete.")

Extraction complete.

In [37]:
print("Comments files:", os.listdir(comments_dir))
print("Entries files:", os.listdir(entries_dir))
print("Likes files:", os.listdir(likes_dir))

Comments files: ['commentAugSept.csv']
Entries files: ['entries1.csv']
Likes files: ['likes.csv']

In [38]:
comments_file = "../data/raw/comments_extracted/commentAugSept.csv"

comment_columns = [
    "comment_id",
    "entry_id",
    "user",
    "source",
    "url",
    "extra1",
    "extra2",
    "timestamp",
    "comment"
]

comments_sample = pd.read_csv(
    comments_file,
    sep="\t",
    header=None,
    names=comment_columns,
    nrows=5,
    dtype=str
)

comments_sample[
    ["comment_id", "entry_id", "user", "timestamp", "comment"]
]

,comment_id,entry_id,user,timestamp,comment
0,e/ed12adf025b5491da54c4ff2c8c5377a/c/c2dbc8151...,e/ed12adf025b5491da54c4ff2c8c5377a,koenigdublin,2010-08-06 15:06:32,В начале 20 века было противостояние идеологи...
1,e/7f6fb13b5a99449bb9dcbb3f8693be73/c/7477fb677...,e/7f6fb13b5a99449bb9dcbb3f8693be73,ilportalinux,2010-08-06 15:06:32,sofferenza? :D
2,e/624ca9226b6526ebdb69f9b46df482c7/c/32c6bf5bc...,e/624ca9226b6526ebdb69f9b46df482c7,guardianuk,2010-08-06 14:45:07,Reel Review video: Catherine Shoard defends Kn...
3,e/2fdf59e075094fe1847137af34eda0f7/c/eb22afe81...,e/2fdf59e075094fe1847137af34eda0f7,nahi,2010-08-06 15:06:32,VMWareじゃなくてVMwareね。
4,e/4d8de05f989d43a4b90bfbfc59751e1c/c/d472f7b81...,e/4d8de05f989d43a4b90bfbfc59751e1c,miocaro,2010-08-06 15:06:31,Anıl havuzdan uzak dur. Sen evde olacaksın :)

In [39]:
entries_file = "../data/raw/entries1_extracted/entries1.csv"

entries_sample = pd.read_csv(
    entries_file,
    sep="\t",
    header=None,
    nrows=5,
    dtype=str
)

entries_sample = entries_sample.rename(
    columns={0: "entry_id"}
)

entries_sample.head()

,entry_id,1,2,3,4,5,6,7,8,9,10,11
0,e/29af803d670fb8d67692095f3ee623e6,newsroom1,Ottawa Citizen - News,http://www.ottawacitizen.com/index.html,\N,\N,2010-08-02 18:43:10,RIM 'will not compromise' BlackBerry security ...,1,http://www.ottawacitizen.com/will+compromise+...,0,NaN
1,e/9c8413a376bec6389be4d46d0812c2bb,mehmetinnet,Mehmetin.Net,http://www.mehmetin.net,\N,\N,2010-08-02 19:15:52,Fethullah Gülen: Referandum siyasî olarak görü...,1,http://www.mehmetin.net/2010/08/fethullah-gul...,0,NaN
2,e/2d658d97842a466a9513f587f85b0e59,mehmetergin,Mehmetin.Net,http://www.mehmetin.net/,\N,\N,2010-08-02 19:15:52,Fethullah Gülen: Referandum siyasî olarak görü...,1,http://www.mehmetin.net/2010/08/fethullah-gul...,0,NaN
3,e/b269ab5d56be4e5e90c1954ecc1ef63a,afriki,NaN,NaN,\N,\N,2010-08-02 16:37:57,Мне тут недавно один дизайнер сказал: «Ну прот...,0,NaN,0,NaN
4,e/74f0a50c374a4ad6bddcbcc60c60cad9,hamsafar,NaN,NaN,\N,\N,2010-08-02 18:54:39,عرض سلام و خسته نباشيد:),0,NaN,0,NaN

In [40]:
likes_file = "../data/raw/likes_extracted/likes.csv"

likes_sample = pd.read_csv(
    likes_file,
    sep="\t",
    header=None,
    names=[
        "user",
        "entry_id",
        "like_timestamp"
    ],
    nrows=5,
    dtype=str
)

likes_sample

               user                            entry_id       like_timestamp
0           yasinde  e/2d4fcaed2d2a4ac1a36571b66da3f16c  2010-04-28 07:17:43
1  socialnewsturkey  e/2d4fcaed2d2a4ac1a36571b66da3f16c  2010-03-02 20:10:02
2             janzu  e/2d4fcaed2d2a4ac1a36571b66da3f16c  2010-03-02 19:50:57
3        mugecerman  e/2d4fcaed2d2a4ac1a36571b66da3f16c  2010-03-02 19:18:38
4           miocaro  e/2d4fcaed2d2a4ac1a36571b66da3f16c  2010-03-02 17:31:31

In [41]:
print("Comment IDs:")
print(
    comments_sample["comment_id"]
    .head()
    .tolist()
)

print("\nComment parent entry IDs:")
print(
    comments_sample["entry_id"]
    .head()
    .tolist()
)

print("\nEntries IDs:")
print(
    entries_sample["entry_id"]
    .head()
    .tolist()
)

print("\nLikes entry IDs:")
print(
    likes_sample["entry_id"]
    .head()
    .tolist()
)

Comment IDs:
['e/ed12adf025b5491da54c4ff2c8c5377a/c/c2dbc8151de546a3a429d379621c9b09', 'e/7f6fb13b5a99449bb9dcbb3f8693be73/c/7477fb67708946aa98b81e14194934bf', 'e/624ca9226b6526ebdb69f9b46df482c7/c/32c6bf5bcbdf4bb59b07ad4df485cfed', 'e/2fdf59e075094fe1847137af34eda0f7/c/eb22afe81f504f33935e2c4666935401', 'e/4d8de05f989d43a4b90bfbfc59751e1c/c/d472f7b8109a41e9b61e411eefd7b1d1']

Comment parent entry IDs:
['e/ed12adf025b5491da54c4ff2c8c5377a', 'e/7f6fb13b5a99449bb9dcbb3f8693be73', 'e/624ca9226b6526ebdb69f9b46df482c7', 'e/2fdf59e075094fe1847137af34eda0f7', 'e/4d8de05f989d43a4b90bfbfc59751e1c']

Entries IDs:
['e/29af803d670fb8d67692095f3ee623e6', 'e/9c8413a376bec6389be4d46d0812c2bb', 'e/2d658d97842a466a9513f587f85b0e59', 'e/b269ab5d56be4e5e90c1954ecc1ef63a', 'e/74f0a50c374a4ad6bddcbcc60c60cad9']

Likes entry IDs:
['e/2d4fcaed2d2a4ac1a36571b66da3f16c', 'e/2d4fcaed2d2a4ac1a36571b66da3f16c', 'e/2d4fcaed2d2a4ac1a36571b66da3f16c', 'e/2d4fcaed2d2a4ac1a36571b66da3f16c', 'e/2d4fcaed2d2a4ac1a36571b66da3f16c']