In [1]:
import pandas as pd

In [2]:
emotion_df = pd.read_csv(
    "../data/processed/emotion_results.csv"
)

engagement_df = pd.read_csv(
    "../data/processed/engagement_data.csv"
)

print("Emotion shape:", emotion_df.shape)
print("Engagement shape:", engagement_df.shape)

Emotion shape: (110336, 14)
Engagement shape: (91071, 3)

In [3]:
final_df = emotion_df.merge(
    engagement_df,
    on="entry_id",
    how="left"
)

print("Final shape:", final_df.shape)

final_df.head()

Final shape: (110336, 16)

,comment_id,entry_id,user,timestamp,comment_clean,anger,disgust,fear,joy,neutral,sadness,surprise,Top_Emotion,Top_Emotion_Score,CommentCount,like_count
0,e/624ca9226b6526ebdb69f9b46df482c7/c/32c6bf5bc...,e/624ca9226b6526ebdb69f9b46df482c7,guardianuk,2010-08-06 14:45:07,Reel Review video: Catherine Shoard defends Kn...,0.010169,0.008245,0.003183,0.428729,0.490051,0.004336,0.055287,neutral,0.490051,1,0
1,e/967b4db48fa74021b24ccbc93c55a61c/c/57905e983...,e/967b4db48fa74021b24ccbc93c55a61c,massoptimization,2010-08-06 15:06:44,Article by at 2010-08-06 09:42:14 Categorized ...,0.004119,0.001753,0.002665,0.005910,0.852355,0.019294,0.113904,neutral,0.852355,1,0
2,e/79e585effdf640e988539e2dd68c2c6d/c/853946596...,e/79e585effdf640e988539e2dd68c2c6d,sheribabysph,2010-08-06 15:06:44,Happy Friday! @Skyblue101 and @TropicsZ4: Matc...,0.003618,0.000299,0.001818,0.844965,0.027604,0.005352,0.116344,joy,0.844965,1,0
3,e/01e9a149fff85ff948972896145d3d65/c/e87986e73...,e/01e9a149fff85ff948972896145d3d65,inhabitat24,2010-08-06 15:06:27,Yesterday the enviously green city of Portland...,0.013171,0.016564,0.008067,0.069312,0.752039,0.004490,0.136357,neutral,0.752039,2,0
4,e/01e9a149fff85ff948972896145d3d65/c/c70184cfd...,e/01e9a149fff85ff948972896145d3d65,inhabitat24,2010-08-06 15:06:27,Yesterday the enviously green city of Portland...,0.013171,0.016564,0.008067,0.069312,0.752039,0.004490,0.136357,neutral,0.752039,2,0

In [4]:
print(
    final_df[
        ["like_count", "CommentCount"]
    ].isna().sum()
)

like_count      0
CommentCount    0
dtype: int64

In [5]:
final_df[
    [
        "comment_clean",
        "Top_Emotion",
        "Top_Emotion_Score",
        "like_count",
        "CommentCount"
    ]
].head()

,comment_clean,Top_Emotion,Top_Emotion_Score,like_count,CommentCount
0,Reel Review video: Catherine Shoard defends Kn...,neutral,0.490051,0,1
1,Article by at 2010-08-06 09:42:14 Categorized ...,neutral,0.852355,0,1
2,Happy Friday! @Skyblue101 and @TropicsZ4: Matc...,joy,0.844965,0,1
3,Yesterday the enviously green city of Portland...,neutral,0.752039,0,2
4,Yesterday the enviously green city of Portland...,neutral,0.752039,0,2

In [6]:
final_df.to_csv(
    "../data/processed/final_emotion_engagement.csv",
    index=False
)

print("Final dataset saved.")
print("Shape:", final_df.shape)

Final dataset saved.
Shape: (110336, 16)